name: Validate addon manifest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sv:
    name: Validate
    runs-on: ubuntu-latest
    # if: ! (github.event_name == 'schedule' && github.repository_owner == 'ScratchAddons')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate .json with schema (all)
        uses: Hans5958/validate-json-action@master
        with:
          schema: https://raw.githubusercontent.com/ScratchAddons/manifest-schema/dist/schema.json
          jsons: addons/*/addon.json
