on:
  push:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Execute script
        id: script
        run: |
          node test.js
        env:
          TEST_ENV_STUFF: "abcdefg"